import { Site, PouringLog } from './types';

export const INITIAL_SITES: Site[] = [
  { id: 'site-1', name: '대구 범어 자이 S&D', code: 'DG-BM-01' },
  { id: 'site-2', name: '평택역 센트럴시티 현대 (2공구)', code: 'PT-CC-02' },
  { id: 'site-3', name: '용인 SK FAB 지원 부속시설', code: 'YI-SK-01' },
  { id: 'site-4', name: '탕정자이 GS', code: 'TJ-GS-01' },
  { id: 'site-5', name: '신반포 22차 현대ENG', code: 'BP-22-HD' },
  { id: 'site-6', name: '평촌 자이 퍼스니티(1공구)', code: 'PC-XI-01' },
  { id: 'site-7', name: '대우 고덕 민간참여(1공구)', code: 'GD-DW-01' },
  { id: 'site-8', name: '포항데이터 센터 현대', code: 'PH-DC-HD' },
  { id: 'site-9', name: '하남교산 대우', code: 'HN-KS-DW' },
];

export const INITIAL_LOGS: PouringLog[] = [
  {
    id: 'log-1',
    site_id: 'site-1',
    category: '1',
    date: '2026-08-01',
    building: '101동',
    floor: '12층',
    member_type: '슬라브',
    min_temp: 22.5,
    max_temp: 31.0,
    weather: '맑음',
    remicon_company: '유진기업(주)',
    strength: '24MPa',
    volume: 180,
    curing_watering: '1일 3회 살수 완료',
    curing_protection: '습윤양생포(피복) 보양',
    remarks: '서중 콘크리트 관리 적용'
  },
  {
    id: 'log-2',
    site_id: 'site-1',
    category: '2',
    date: '2026-08-02',
    building: '102동',
    floor: '10층',
    member_type: '벽체/기둥',
    min_temp: 21.0,
    max_temp: 29.5,
    weather: '흐림',
    remicon_company: '삼표산업(주)',
    strength: '27MPa',
    volume: 145,
    curing_watering: '지속 살수 소독',
    curing_protection: '거푸집 유효 유지',
    remarks: '초결 및 종결시간 양호'
  },
  {
    id: 'log-3',
    site_id: 'site-1',
    category: '3',
    date: '2026-08-03',
    building: '101동',
    floor: '13층',
    member_type: '슬라브',
    min_temp: 23.0,
    max_temp: 32.5,
    weather: '맑음',
    remicon_company: '유진기업(주)',
    strength: '24MPa',
    volume: 195,
    curing_watering: '살수 4회실시',
    curing_protection: '양생시트 덮개 양생',
    remarks: '균열 점검 필'
  },
  {
    id: 'log-4',
    site_id: 'site-2',
    category: '1',
    date: '2026-08-01',
    building: '201동(A구역)',
    floor: '5층',
    member_type: '벽체',
    min_temp: 20.5,
    max_temp: 28.0,
    weather: '비',
    remicon_company: '아주산업(주)',
    strength: '30MPa',
    volume: 210,
    curing_watering: '우천시 자연 습윤',
    curing_protection: '비닐 천막 방수 보양',
    remarks: '우천 대비 보호조치 실시'
  },
  {
    id: 'log-5',
    site_id: 'site-3',
    category: '1',
    date: '2026-08-02',
    building: 'FAB동',
    floor: '지하2층',
    member_type: 'MAT 기초',
    min_temp: 19.5,
    max_temp: 27.5,
    weather: '맑음',
    remicon_company: '쌍용레미콘',
    strength: '35MPa',
    volume: 520,
    curing_watering: '살수기 자동 살수',
    curing_protection: '단열 및 수분유지포 보양',
    remarks: '매스콘크리트 수화열 제어 관리'
  }
];
